### ISSUE TITLE
The release package/source code are missing

### ISSUE THREAD

**Issue by dabi0ne** [airbus-cyber/graylog-plugin-alert-wizard#1]
Hello,

Thanks for the great project, i want to try it but the repository doesn't contain any release or source code.

Is the project still maintained ?

**Comment by dio99** [comment]
hard to build if no code is there :P

**Comment by dlancelin** [comment]
Hello,

Source code will be available soon.

**Comment by dio99** [comment]
great :)

**Comment by dlancelin** [comment]
Hello,

Sorry for the delay. Source code is now available.

**Comment by dio99** [comment]
great thanks im gonna test it.. 
maybe build it as a complete  package with all deps ? since ti requires the 3 other plugins to work 
// Anders

**Comment by dlancelin** [comment]
Thank you dio99 for your great idea. 
However, it can work without the 3 other plugins. 
In fact, the 3 other plugins are only needed to get all the features of the wizard. 
So, depending on your needs, you can use the wizard with or without the other plugins, it's more flexible.

**Comment by dio99** [comment]
yes i think so :) since the options to use the aggregations is handy its better to have all options from my point of view at start.. then rather to  add it later when needed :)
since the stuff we build is based on kubernetes and that creates some deployemnts with the jar files as binary in the config-map yml file :)

**Comment by dio99** [comment]
im testing it on 2.5.1 now and get this error in gui from wizzard
Could not create alert rule
Creating alert rule failed with status: cannot PUT https://graylog1/api/plugins/com.airbus_cyber_security.graylog/alerts (400)

**Comment by dlancelin** [comment]
I will add compatibility with 2.5.1

**Comment by dio99** [comment]
okie great :)

**Comment by dlancelin** [comment]
I have released a new version for Graylog 2.5
