### ISSUE TITLE
Cannot access Advanced settings & Try button does not work

### ISSUE THREAD

**Issue by soulmaster43** [airbus-cyber/graylog-plugin-alert-wizard#10]
Hi,

I installed this plugin on a graylog-server version 3.1.2-1 which is running on top of Ubuntu 18 and I noticed some issues:

- The Advanced Settings does not seems to work
  Redirects me to http://127.0.0.1:9000/alerts/conditions/5d8a1ad641e23803aff0c11d/1c1ee31c-3da7-4bdd-b4d7-0807ce374523

"Page not found
The party gorilla was just here, but had another party to rock.
Oh, party gorilla! How we miss you! Will we ever see you again?"

- The Try button doesn't seem to work (not clickable)

Thank you

**Comment by soulmaster43** [comment]
Hi Thomas,

Thank you for your reply.

I understand that the plugin was not meant for version 3.1 yet I am wondering if there is a plan to update it.
After all, basic functionality is present and may not require a radical re-write.

Thank you.

**Comment by tomasnk** [comment]
Hi,
The plugin will be updated, I hope for the end of this year.

**Comment by TiNico22** [comment]
closed and replaced by #11 to clarify the issue
