### ISSUE TITLE
Use Priority instead of Severity

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#100]
When we created Logging Alert plugin we created the field Severity because there was no equivalent in Graylog.
But now there is the Priority field.
Priority has only 3 levels, and Severity 4, but it may be enough.

**Comment by c8y3** [comment]
This is a breaking change. It seems to me that it implies a migration step (exporting/importing all rules). The mapping from current severity levels to priorities needs to be defined in order to have the import accept ancient rules.

**Comment by VincentD06** [comment]
The mapping for this feature is : 

| Severity | Priority |
|---|---|
| INFO | LOW |
| FAIBLE | LOW |
| MOYENNE | NORMAL |
| HAUTE | HIGH |

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0
