### ISSUE TITLE
Compatibility with Graylog 3.1

### ISSUE THREAD

**Issue by TiNico22** [airbus-cyber/graylog-plugin-alert-wizard#11]
Add compatibility with Graylog 3.1 
Release 3.0 are only compatible with Graylog 3.0

replace #10 issue from @soulmaster43

**Comment by estein9825** [comment]
Any idea when this will be updated to 3.1?

**Comment by tomasnk** [comment]
We plan to update and release the plugins at the end of the quarter.

**Comment by TiNico22** [comment]
Replaced by #16
