### ISSUE TITLE
Incorrect french translation of the sum statistics condition

### ISSUE THREAD

**Issue by c8y3** [airbus-cyber/graylog-plugin-alert-wizard#112]
In french, both the sum and sum of square statistical condition are labeled `Somme des carrés`. The sum should be simply translated `Somme`.
To reproduce, set the browser language to french. Go to the creation page of a new rule of type statistics. The label in the statistical condition drop-down is incorrect for sum.

**Comment by frantz45** [comment]
I've tested with Wizard v5.1.0 and I confirm it's fixed
