### ISSUE TITLE
Creating an alert with a field condition without the type breaks the alert list

### ISSUE THREAD

**Issue by c8y3** [airbus-cyber/graylog-plugin-alert-wizard#120]
This problem is reproduced as follows:
* create a new count rule with a field condition with a name and value but without selecting the condition type
* button save can be clicked (it should still be greyed out)
* a request POST plugins/com.airbus_cyber_security.graylog.wizard/alerts is sent to the server with the field_rule type being an empty string (it is supposed to be an integer)
* there is a stack trace and then the list of alert rules can not be displayed anymore

=> 
* The save button should not be greyed out.
* The server should reject the POST request without corrupting the database

**Comment by frantz45** [comment]
I confirm it's fixed in Wizard v5.2.0
