### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#13]
You fixed a performance issue in v3.0.1 but I still have a performance issue with the Wizard.
When I create a rule the following fields are slow compared to others :
- Field value
- Number of logs
- Period

When I edit a rule, all fields are slow, even clicking on an item in a list.
On my workstation I find the firefox process takes 100% CPU when the issue happens.

Wizard v3.0.1.
Graylog v3.0.2.

**Comment by TiNico22** [comment]
@frantz45 can you confirm this issue is still relevant and present in latest version 3.3.0

**Comment by frantz45** [comment]
> 
> 
> @frantz45 can you confirm this issue is still relevant and present in latest version 3.3.0

In 3.3.0 it's faster than old versions. It's quite comfortable to use this plugin.
However I think it can still be optimized because when you type something in a field value the Firefox process still many increases the CPU consumption.
It seems something is refreshed or triggered each time a character is typed in this field.

**Comment by frantz45** [comment]
This issue is not present anymore in Wizard v4.0.0 (Graylog v4.1.6 and Firefox v78 ESR).
It's totally smoothed and the CPU consumption is totally normal (there isn't any spike like before).
