### ISSUE TITLE
Test button doesn't work

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#130]
https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/74

**Comment by c8y3** [comment]
Remove the Test button. 
In the list of alert rules, add a new action: Search (with the play icon) which brings us into the search page with the query and stream configured, with a period of 1 day.

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0.
Maybe it would have been nice to open the search in another tab, I'll open a new issue if needed
