### ISSUE TITLE
Error when importing a rule with a null description

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#132]
POST /api/plugins/com.airbus_cyber_security.graylog.wizard/alerts with the null value for the description field

It will return a 400 Bad request: Cannot construct instance of [...], problem: Null getDescription [...]

(This error happens when I tried to import a rule with a null description)
(I don't know how it is possible to get a null description because it always seems to be an empty string instead of a null value when there is no description)

**Comment by c8y3** [comment]
Is this still necessary? Do you still have rules with null descriptions?
Could you attach an example of such rule to the issue?
Thank you.

**Comment by c8y3** [comment]
When there is no description, the export is supposed to write a JSON file with the description field set to empty string (and not null). It would be great to be able to identify the scenario which led to the generation of a JSON file with a null description and fix this issue at its root rather than make the import code more complex than necessary.

**Comment by frantz45** [comment]
This should not happen. It must be come from a script moifying the JSON.
This issue won't be fixed at the moment.
Issue is "in observation" for 1 year. If it happens again it wll be fixed, otherwise it will be refused.

**Comment by frantz45** [comment]
Issue has just happened, I didn't use any script, I've only exported rules from a Wizard v4.4.1.
I've more than 100 rules in the JSON and only 1 rule has a null description.

**Comment by c8y3** [comment]
It would be interesting to export the rule alone. And try to reproduce the problem starting from an empty graylog.

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0
