### ISSUE TITLE
GET on statistical rules is missing condition parameter field

### ISSUE THREAD

**Issue by c8y3** [airbus-cyber/graylog-plugin-alert-wizard#143]
When doing a GET request on a statistical rule, there seems to be no field in condition_parameters anymore.
This also impacts the exported data which relies on the get.

To reproduce:
* create a statistical rule
* then edit the statistical rule again
* the field is missing

**Comment by c8y3** [comment]
Accompanying test:
    def test_get_alert_rule_should_return_correct_field(self):
        title = 'rule_title'
        self._api.create_alert_rule_statistics(title, _PERIOD)
        retrieved_alert_rule = self._graylog.get_alert_rule(title)
        self.assertEqual('a', retrieved_alert_rule['condition_parameters']['field'])

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0
