### ISSUE TITLE
Authentication error with lists

### ISSUE THREAD

**Issue by Sinagot** [airbus-cyber/graylog-plugin-alert-wizard#17]
Hi,

I just downloaded the 3.1 version of the plugin, and I'm encoutering the following issue with lists :

- Create a new list "Whitelist_Scripts"
- Edit the header section in data adapter with name = Authorization and Value : dG90bzptb3RkZXBhc3Nl (base64 user and password as requested)
- When I try to lookup a value (name of the list), I get the following error in server.log :

` WARN  [HTTPJSONPathDataAdapter] HTTP request for key <Whitelist_Scripts> failed: Response{protocol=http/1.1, code=401, message=Unauthorized, url=http://192.168.198.130:9000/api/plugins/com.airbus_cyber_security.graylog/lists/Whitelist_Scripts}`

I tried with value = basic dG90bzptb3RkZXBhc3Nl, with same result.

Rules and alerting are working fine.

Graylog version : 3.0.2

**Comment by Sinagot** [comment]
Ok, just found out what was the problem : in the value, Basic is case sensitive and need a uppercase as first letter.

Maybe you should add a specific comment for this part as your readme file is not very clear.

**Comment by TiNico22** [comment]
Readme.md updated to avoid this
Thanks for the feedback
