### ISSUE TITLE
Plugin causes Streams page to load slowly

### ISSUE THREAD

**Issue by ion-storm** [airbus-cyber/graylog-plugin-alert-wizard#2]
I noticed that when there is a correlation steam setup with the wizard even in disabled status the plugin causes the streams page to load slowly almost up to 15-30 seconds.  Deleting all rules in the wizard or disabling the plugin resolves the slow loading issue.  I have about 50 streams  that are non-wizard streams, not sure if this helps.

**Comment by dlancelin** [comment]
Hi,
Sorry for my late answer.
Could you tell me how many streams have you configured with the wizard?
With your 50 streams that are non-wizard, how long does it take to load your streams page?
Also, could you tell me what is your version of Graylog?

**Comment by ion-storm** [comment]
takes about 30s

**Comment by dlancelin** [comment]
What is your version of Graylog? and the plugin version ?
