### ISSUE TITLE
Use token instead user:password for lists

### ISSUE THREAD

**Issue by Sinagot** [airbus-cyber/graylog-plugin-alert-wizard#20]
Hi,

Could it be possible to use a token instead the user:password (base64) combo to authenticate for lists ?

**Comment by frantz45** [comment]
Did you try to use the token value as user and the word "token" as password ?
I think it should work.
Example:
echo -n 'sdpfojqsiodhfioqshfoiqs23dsf34:token' | base64

**Comment by frantz45** [comment]
I confirm you can use a token, I've updated the documentation: https://github.com/airbus-cyber/graylog-plugin-alert-wizard/pull/45
