### ISSUE TITLE
Enhancement - Use checkbox for multiple selection

### ISSUE THREAD

**Issue by Sinagot** [airbus-cyber/graylog-plugin-alert-wizard#24]
Use checkbox to select multiple rules to enable/disable/remove.

**Comment by frantz45** [comment]
It would be nice to add global buttons instead of having individual buttons on each line

**Comment by frantz45** [comment]
From Graylog v5.1 (maybe from v5.0) this behavior exists for Streams, Dashboards... Maybe we can use this widget to do the same

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0. Very cool feature thank you
