### ISSUE TITLE
how to use in graylog V3.3.3

### ISSUE THREAD

**Issue by wangmenghub** [airbus-cyber/graylog-plugin-alert-wizard#29]
how to use in graylog-server V3.3.3?

**Comment by frantz45** [comment]
This plugin is not compatible with Graylog v3.3.x yet.
At the moment it's compatible with Graylog 3.2.x.

**Comment by TiNico22** [comment]
3.3 support available 
https://github.com/airbus-cyber/graylog-plugin-alert-wizard/releases
