### ISSUE TITLE
Compatibility with Graylog 3.0

### ISSUE THREAD

**Issue by Fendril** [airbus-cyber/graylog-plugin-alert-wizard#3]
Hi,
I tried to install the plugin within a Graylog 3.0.
I don't have any error message but I still don't have the "Wizard" tab to use it.
Any chance to make it usable on a 3.0 instance? Will it be complicated to change source and recompile it by myself?
Thanks for any answer.

**Comment by TiNico22** [comment]
The support for 3.0 is not planned yet.
It will come later this year. We update this ticket when more information will be available

**Comment by wullensm** [comment]
Hi, 
I've just trie to install the last version of Plugin. I can't access to "wizard" tab. 
The error message is "Server curruntly unavailable".

A red border still apears contains
Could not retrieve alert rules with additional data
Fetching alert rules failed with status: Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

Can you help me ?

**Comment by dlancelin** [comment]
Hi,
Could you tell me what is the version of your Graylog server? And also the version of the plugin?

**Comment by wullensm** [comment]
Hi, 
I use graylog-server 2.4.6 and the plugin 1.1.1.

**Comment by TiNico22** [comment]
@wullensm 
for the 2.4, you need the 1.0.0 version of the plugin. The 1.1.x run only on 2.5 
the compatibility matrix is available here : https://github.com/airbus-cyber/graylog-plugin-alert-wizard#graylog-and-plugins-version-compatibility

**Comment by macaty** [comment]
pls update and Compatibility with Graylog 3.0

**Comment by TiNico22** [comment]
> 
> pls update and Compatibility with Graylog 3.0

Hello @macaty 
The comment https://github.com/airbus-cyber/graylog-plugin-alert-wizard/issues/3#issuecomment-464138428 still apply. As soon as we have more info to share about the potential release date we will update this issue.
If people are willing to contribute, don't hesitate to ask.

**Comment by TiNico22** [comment]
Graylog 3.0 support should come early Q3 this year.

**Comment by TiNico22** [comment]
Available for v3
Please create a new ticket if any issue found with the v3
