### ISSUE TITLE
Notification Alert reset

### ISSUE THREAD

**Issue by kilyan-sair** [airbus-cyber/graylog-plugin-alert-wizard#5]
Hi
Once my rule is created, I return to modify it, I save it and the notification in "advanced settings" is reset with the default settings.
I use Wizard plugin 1.1.0.

Thanks for any answer

**Comment by dlancelin** [comment]
The issue has been fixed with the version [1.1.2](https://github.com/airbus-cyber/graylog-plugin-alert-wizard/releases/tag/1.1.2).
