### ISSUE TITLE
Change the advanced settings button

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#57]
The "advanced settings" button is not as usefull as it was.
In older versions of Graylog there was a page to configure the alert conditions and the notification. And the advanced settings button allowed reaching this page.
In recent versions this page doesn't exist anymore and the advanced settings button bring you to the event definition.
I think you could rename "advanced settings" with "event definition" and add a new button "notification".

**Comment by c8y3** [comment]
Do you mean the "advanced settings" button in the alert rule list, or at the end of the alert rule creation?

**Comment by frantz45** [comment]
Initially I meant the button in the alert rules list.
But you're right the same button is displayed at the end of the alert rule creation. You can also replace this button with the 2 new buttons.

**Comment by frantz45** [comment]
I've found this button in another place: when you edit a rule it is displayed in the top right corner. You can replace this button with the 2 new buttons.

**Comment by frantz45** [comment]
I confirm it's fixed in v4.0.0
