### ISSUE TITLE
Disabling a wizard rule should disable the event definition

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#58]
When you disable a rule from the Wizard it pauses the corresponding streams.
It works well because logs can't go into the streams anymore, so the event definition doesn't find any log.
But the event definition is still trying to find events every X minutes.
It would be cleaner to disable the event definition (in addition to pause the streams).

**Comment by frantz45** [comment]
In fact I think it's better to keep the streams ingesting logs instead of pausing them.

**Comment by frantz45** [comment]
It's very problematic for "less than 1" rules, because they will always trigger as there is no log in the Stream. Pausing the Event Definition is mandatory for this use case.

**Comment by c8y3** [comment]
Cases to handle:
* disable a rule => disable the corresponding event definition
* disable a OR rule => disable the two corresponding event definitions
* enable a rule => enable the corresponding event definitions back

**Comment by c8y3** [comment]
It seems the disabling/enabling of streams is currently exclusively done on the GUI side (see https://github.com/airbus-cyber/graylog-plugin-alert-wizard/blob/4.4.1/src/web/wizard/components/AlertRuleList.jsx#L106)
The disabled state of the rule is based on the disabled state of the stream.
Likewise, methods [enable](https://github.com/Graylog2/graylog2-server/blob/4.3.13/graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js#L244) and [disable](https://github.com/Graylog2/graylog2-server/blob/4.3.13/graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js#L267) of the EventDefinitionsStore should prove useful to fix this issue.

**Comment by frantz45** [comment]
I've tested with Wizard v5.1.0 and I confirm it works well
