### ISSUE TITLE
Compatibility with Graylog 4.3

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#75]
Be careful with https://github.com/Graylog2/graylog2-server/pull/11550

**Comment by c8y3** [comment]
Maybe we should wait for the version which include this correction: https://github.com/Graylog2/graylog2-server/commit/0c91082789009d09e8433ddf26f59178befee701. This will make the migration easier for the correlation count plugin.

**Comment by frantz45** [comment]
I confirm version v4.4.0 works well with Graylog v4.3.8.
