### ISSUE TITLE
Wizard-Link in Main-menu not working

### ISSUE THREAD

**Issue by pulgit** [airbus-cyber/graylog-plugin-alert-wizard#8]
Hi!

Using graylog-plugin-alert-wizard-3.0.0.jar on Graylog v3.0.2+1686930 behind an apache reverse-proxy.

We run graylog via the URL https://security.XXYY.com/graylog . The the "Wizard"-Link in the main-menu should therefore probably point to https://security.XXYY.com/graylog/wizard but instead it points to https://security.XXYY.com/wizard (and therefore fails).

Alltough we cann access the wizard by manually browsing to https://security.XXYY.com/graylog/wizard

Thanks.

**Comment by tomasnk** [comment]
Hi,
It appears that it's not a bug from the plugin itself but from graylog. Please follow  Graylog2/graylog2-server#6149  for updates.

**Comment by mariussturm** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/6150
