### ISSUE TITLE
Set a default value for the "match all/at least one rules"

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#85]
This setting allows to choose if logs must match ALL rules defined or AT LEAST one rule.
This setting is mandatory so default value should be set.
The value "match all" seems fine.

It should also be set in the 2nd block of conditions for rules with multiple blocks (for example an "AND" rule).

**Comment by frantz45** [comment]
@c8y3 I confirm it's fixed for the 1st block but not for the 2nd block (AND and THEN rule types), do you think it's another issue or do you want to fix it in this issue ?

**Comment by c8y3** [comment]
Remove field title_condition.

**Comment by frantz45** [comment]
I confirm it's fixed
