### ISSUE TITLE
Update graylog-plugin-login-alert with latest fixes

### ISSUE THREAD

**Issue by c8y3** [airbus-cyber/graylog-plugin-alert-wizard#89]
Update to 4.1.2 when released, in order to take fix of https://github.com/airbus-cyber/graylog-plugin-logging-alert/issues/38 into account.

**Comment by frantz45** [comment]
Use Github project to follow the issue, so it's not needed to duplicate issues

**Comment by frantz45** [comment]
@c8y3 In fact I'm not confident closing this issue because it isn't exaclty a duplicate, we need to update this dependency

**Comment by frantz45** [comment]
I confirm latest version v4.2.0 of logging alert is included in wizard v4.4.0
