### ISSUE TITLE
Log a warning when a rule has multiple distinct_fields

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#93]
From v4.3.0 it's not supported to import a rule with multiple distinct_fields, only the first one is kept.
A warning log should be generated when it happens.
For example:
WARN The rule "rule_title" has multiple distinct_fields, only the first one will be kept ("field_name")

**Comment by VincentD06** [comment]
I don't reproduce this problem. I try with this file :

[2024-06-26_093707_alert_rules.json](https://github.com/user-attachments/files/16010804/2024-06-26_093707_alert_rules.json)

Import works with versions 4.3.0, 4.3.1, 4.5.0 and 5.2.0.

**Comment by VincentD06** [comment]
Seems to be fix in [this commit](https://github.com/airbus-cyber/graylog-plugin-alert-wizard/commit/e77ecba8d90c505b33e564f99b3e05e42a10a72d)

**Comment by VincentD06** [comment]
OK. I added a user notification on the import page when this case appears.
