### ISSUE TITLE
Test OpenSearch

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-alert-wizard#95]
OpenSearch is supported from Graylog v4.3 and new ElasticSearch versions won't be supported anymore.
It should be nice to update the tests to check if our plugins work well with OpenSearch.
Have all tests pass with OpenSearch in Continuous Integration

**Comment by c8y3** [comment]
See:
* https://github.com/Graylog2/graylog2-server/issues/12735
* https://go2docs.graylog.org/5-0/planning_your_deployment/upgrading_to_opensearch.htm?tocpath=Upgrading%20Graylog%7COpenSearch%7CMoving%20from%20Elasticsearch%20to%20OpenSearch%7C_____0

**Comment by c8y3** [comment]
Do not forget to check the "Software Interoperability Chart" (https://go2docs.graylog.org/5-0/planning_your_deployment/planning_your_upgrade_to_opensearch.htm?tocpath=Upgrading%20Graylog%7COpenSearch%7CMoving%20from%20Elasticsearch%20to%20OpenSearch%7C_____2)

**Comment by c8y3** [comment]
And also:
* https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/index/#important-settings
* https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/docker/#sample-docker-composeyml

**Comment by frantz45** [comment]
I've tested with Wizard v5.1.0 and I confirm there is no issue with OpenSearch v2.7.0
